# This is a basic workflow to help you get started with Actions

name: Call a reusable workflow #this is caller

on:

  push:
   branches:
    - main

jobs:
  call-workflow:
    uses: Anjanak99/githubactions/.github/workflows/trial.yml@main
    
    
    
    
    
    
    

 
