# This is a basic workflow to help you get started with Actions

name: Call a reusable workflow #this is caller

on:
 workflow_dispatch:
 # push:
  # branches:
   # - main

jobs:
  #call-workflow:
   # uses: Anjanak99/githubactions/.github/workflows/trial.yml@main
    

  call-workflow-passing-data:
    uses: Anjanak99/githubactions/.github/workflows/secret.yml@main
    with:
      username: anjana
    secrets:
      token: ${{ secrets.ABCD }}
    
    
    
    
    
    
    

 
