# This is a basic workflow to help you get started with Actions

name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: Anjanak99/githubactions/.github/workflows/actions.yml@main

 
