# This is a basic workflow to help you get started with Actions

name: Calling_secret

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
#  call-workflow:
#  uses: Anjanak99/githubactions/.github/workflows/blank.yml@v1

 call-workflow-passing-data:
  uses: Anjanak99/githubactions/.github/workflows/secret_reusable.yml@main
  with:
      username: Anjana
  secrets:
      token: ${{ secrets.ABCD }}
      runs-on: ubuntu-latest






