# This is a basic workflow to help you get started with Actions

name: secret_reusable

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
       - run: echo " username:${{ inputs.username }} & keyname:${{ secrets.token }}"
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

