# This is a basic workflow to help you get started with Actions

name: secret_reusable

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true
        
  workflow_dispatch:

jobs:
  example_job:
    name: Pass input and secrets
    runs-on: ubuntu-latest
    steps:
       - run: echo " username:${{ inputs.username }} & keyname:${{ secrets.token }}"





