# This is a basic workflow to help you get started with Actions

name: same_variable_intwojobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.test}}
      output2: ${{steps.step2.outputs.test}}     
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: step1
        run: echo "::set-output name =test::hello"
      - id: step2
        run: echo "::set-output name =test::world"
      
  job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - run: echo ${{ needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      
       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
     # - name: Run a one-line script
     #   run: echo Hello, world!


